/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriveRouteRouteImport } from './routes/drive/route'
import { Route as DriveIndexRouteImport } from './routes/drive/index'
import { Route as DriveStarredRouteImport } from './routes/drive/starred'
import { Route as DriveTrashRouteImport } from './routes/drive/trash'
import { Route as DriveFoldersFolderIdRouteImport } from './routes/drive/folders.$folderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRouteRoute = DriveRouteRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveIndexRoute = DriveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriveRouteRoute,
} as any)
const DriveStarredRoute = DriveStarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => DriveRouteRoute,
} as any)
const DriveTrashRoute = DriveTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => DriveRouteRoute,
} as any)
const DriveFoldersFolderIdRoute = DriveFoldersFolderIdRouteImport.update({
  id: '/folders/$folderId',
  path: '/folders/$folderId',
  getParentRoute: () => DriveRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drive': typeof DriveRouteRouteWithChildren
  '/drive/starred': typeof DriveStarredRoute
  '/drive/trash': typeof DriveTrashRoute
  '/drive/': typeof DriveIndexRoute
  '/drive/folders/$folderId': typeof DriveFoldersFolderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drive/starred': typeof DriveStarredRoute
  '/drive/trash': typeof DriveTrashRoute
  '/drive': typeof DriveIndexRoute
  '/drive/folders/$folderId': typeof DriveFoldersFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drive': typeof DriveRouteRouteWithChildren
  '/drive/starred': typeof DriveStarredRoute
  '/drive/trash': typeof DriveTrashRoute
  '/drive/': typeof DriveIndexRoute
  '/drive/folders/$folderId': typeof DriveFoldersFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drive'
    | '/drive/starred'
    | '/drive/trash'
    | '/drive/'
    | '/drive/folders/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drive/starred'
    | '/drive/trash'
    | '/drive'
    | '/drive/folders/$folderId'
  id:
    | '__root__'
    | '/'
    | '/drive'
    | '/drive/starred'
    | '/drive/trash'
    | '/drive/'
    | '/drive/folders/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriveRouteRoute: typeof DriveRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive/': {
      id: '/drive/'
      path: '/'
      fullPath: '/drive/'
      preLoaderRoute: typeof DriveIndexRouteImport
      parentRoute: typeof DriveRouteRoute
    }
    '/drive/starred': {
      id: '/drive/starred'
      path: '/starred'
      fullPath: '/drive/starred'
      preLoaderRoute: typeof DriveStarredRouteImport
      parentRoute: typeof DriveRouteRoute
    }
    '/drive/trash': {
      id: '/drive/trash'
      path: '/trash'
      fullPath: '/drive/trash'
      preLoaderRoute: typeof DriveTrashRouteImport
      parentRoute: typeof DriveRouteRoute
    }
    '/drive/folders/$folderId': {
      id: '/drive/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/drive/folders/$folderId'
      preLoaderRoute: typeof DriveFoldersFolderIdRouteImport
      parentRoute: typeof DriveRouteRoute
    }
  }
}

interface DriveRouteRouteChildren {
  DriveStarredRoute: typeof DriveStarredRoute
  DriveTrashRoute: typeof DriveTrashRoute
  DriveIndexRoute: typeof DriveIndexRoute
  DriveFoldersFolderIdRoute: typeof DriveFoldersFolderIdRoute
}

const DriveRouteRouteChildren: DriveRouteRouteChildren = {
  DriveStarredRoute: DriveStarredRoute,
  DriveTrashRoute: DriveTrashRoute,
  DriveIndexRoute: DriveIndexRoute,
  DriveFoldersFolderIdRoute: DriveFoldersFolderIdRoute,
}

const DriveRouteRouteWithChildren = DriveRouteRoute._addFileChildren(
  DriveRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriveRouteRoute: DriveRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
