/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriveRouteRouteImport } from './routes/drive/route'
import { Route as DriveIndexRouteImport } from './routes/drive/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRouteRoute = DriveRouteRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveIndexRoute = DriveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriveRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drive': typeof DriveRouteRouteWithChildren
  '/drive/': typeof DriveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drive': typeof DriveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drive': typeof DriveRouteRouteWithChildren
  '/drive/': typeof DriveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drive' | '/drive/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drive'
  id: '__root__' | '/' | '/drive' | '/drive/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DriveRouteRoute: typeof DriveRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive/': {
      id: '/drive/'
      path: '/'
      fullPath: '/drive/'
      preLoaderRoute: typeof DriveIndexRouteImport
      parentRoute: typeof DriveRouteRoute
    }
  }
}

interface DriveRouteRouteChildren {
  DriveIndexRoute: typeof DriveIndexRoute
}

const DriveRouteRouteChildren: DriveRouteRouteChildren = {
  DriveIndexRoute: DriveIndexRoute,
}

const DriveRouteRouteWithChildren = DriveRouteRoute._addFileChildren(
  DriveRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DriveRouteRoute: DriveRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
